### ISSUE TITLE
Issue with install.sh

### ISSUE THREAD

**Issue by h76** [cskcsk/shellforge2#1]
Hi,

I noticed that you posted an issue in the shellforge4 repository. I was wondering if you were able to get that code to work because when I try to use install.sh, I get these errors:

Lydias-MacBook-Pro:shellforge4 lydiahogan$ sh /Users/lydiahogan/git/shellforge4/sflib/install.sh
/Users/lydiahogan/git/shellforge4/sflib/install.sh: line 7: ./gensflib.py: No such file or directory

When I run the same command in the sflib directory, I get this error:
Traceback (most recent call last):
File "./gensflib.py", line 220, in 
gen_sflib(source,dest)
File "./gensflib.py", line 88, in gen_sflib
open(dest+"common/sftypes.h","w").write(open(source+"common/sftypes.h").read())
IOError: [Errno 2] No such file or directory: '/usr/include//sflib/common/sftypes.h'

Any suggestions on how to fix this?

**Comment by h76** [comment]
Nevermind, I figured it out.
